# Render Blueprint for Gezira Scheme GIS
# This file defines all services needed for deployment

services:
  # Backend API Service
  - type: web
    name: gezira-gis-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: DATABASE_URL
        fromDatabase:
          name: gezira-gis-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://gezira-gis-frontend.onrender.com

  # Frontend Static Site
  - type: web
    name: gezira-gis-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    envVars:
      - key: VITE_API_URL
        value: https://gezira-gis-backend.onrender.com/api

databases:
  - name: gezira-gis-db
    databaseName: gezira_scheme
    user: gezira_admin
    plan: free
    region: oregon
    postgresMajorVersion: 16
